### ISSUE TITLE
issue with display and disabled properties

### ISSUE THREAD

**Issue by joelbordes** [gfranko/jquery.selectBoxIt.js#134]
if the original select box has a "display:none" css property, selectboxit still displays it. I went around the issue by inserting the select box in a hidden container div. However, when the container div is displayed, the selectboxit is displayed properly but is now disabled.

**Comment by bhumiradixweb** [comment]
You forgot to make changes in **jquery.selectBoxIt.min.js** file for this issue. please change that too.
