### ISSUE TITLE
Options z-index question

### ISSUE THREAD

**Issue by jasendw1979** [gfranko/jquery.selectBoxIt.js#139]
I'm working on a new page, and I have a select box that allows the user to change the grouping in the jqGrid (jQuery plugin). Using the standard HTML select works fine, and the options list is displayed on top of the jqGrid below it. However, when I make the box a selectBoxIt box, the options are always displayed behind the grid. I've tried changing the z-index of the select box element and the jqGrid, but I can't seem to get the options to be displayed on top. 

The grid has a z-index of 1, and the div that houses the select box has a z-index of 10000. I've also set ".selectboxit-container .selectboxit-options" to have a z-index of 9999999, but no matter what I set them to, the options are always displayed behind. Any thoughts on what I could be missing?

**Comment by iVoteSize** [comment]
Thanks Limos, that css you suggested above (Feb 4, 2014) is what I was looking for to have my list appear without being 'cut-off'
