### ISSUE TITLE
Drupal and selectBoxIt.js

### ISSUE THREAD

**Issue by jrsmith17** [gfranko/jquery.selectBoxIt.js#145]
I was trying to use the selectBoxIt plugin with Drupal. For reference, I have the latest versions of Drupal and jquery installed. In my theme's info file, I have the reference to selectboxit.js before all.js (where I call the function). Also, I used the custom js builder on your site and grabbed core + mobile. I downloaded the minified version. I am running into these errors:

Uncaught TypeError: Object function (j,s){return new b.fn.init(j,s)} has no method 'widget' selectBox.js:2
Uncaught TypeError: Object #<Object> has no method 'selectBoxIt' 

I tried googling this but nothing I found was relevant. I'm guessing it has something to do with the first error, but I don't know what it could mean.

**Comment by kristin-e** [comment]
I am working with Drupal 8 and I'm coming across the following error:
$.widget is not a function(…)

I have listed both jquery and jquery-ui (as it includes widget) as dependencies. Anyone else come across this?
