### ISSUE TITLE
Not rendering selectBoxIt correctly when in div with display:none

### ISSUE THREAD

**Issue by jnorrisdesign** [gfranko/jquery.selectBoxIt.js#149]
I have a <select> element in a div that is initially hidden (via display:none) when the page loads. When a user clicks a link that div is changed to display its content (including the <select> element).

The width of the selectBoxIt element doesn't appear to be figured correctly.

Here is a jFiddle showing the issue.
http://jsfiddle.net/dJzhV/1/

Thanks for the help and the great plugin.

**Comment by frafor1988** [comment]
I had a similar issue inside a hidden div using flexbox, and it was caused by max-height: 0px applied to:
.selectboxit-container .selectboxit-options
So then i just forced
.selectboxit-container .selectboxit-options { max-height: none !important; } via CSS and it's working fine.
