### ISSUE TITLE
How to validate selectboxIt with Jquery Validation Engine

### ISSUE THREAD

**Issue by Joshqua** [gfranko/jquery.selectBoxIt.js#164]
Hi Greg,

I tried many things but I cant figure out how to validate selectboxIt with Jquery Validation Engine (https://github.com/posabsolute/jQuery-Validation-Engine).

Any chance to validate selectboxIt with Jquery Validation Engine?

Kind Regards
Ozan

**Comment by prashmi9** [comment]
I am using selectboxit with angular and found that it doesn't support the "required" attribute. I tried to custom the function onchange but with no success.
