### ISSUE TITLE
Difficulty loading data via json call

### ISSUE THREAD

**Issue by mzadig** [gfranko/jquery.selectBoxIt.js#171]
Greg,
I'm new to SelectBoxIt, but it looks great.
I am trying to load the box with remote data via a $ajax() call to my local server.   I don't believe I have the call correct.
My code is as follows:

```
$(function() {

  $("select").selectBoxIt({
        populate: { 'data' : $.ajax
                       ({
                           type: "GET",
                           url: "home/getData",
                           data: "",              
                           cache: false,
                           success: function (html) {
                               d = html;
                               alert(d);

                           },
                           error: function (jqXHR, textStatus, errorThrown) {
                               alert("ajax error" + errorThrown);
                           }
                       }
                       )
                   }
    });
```

});

The call is returning the following structure which appears in the alert(d) display:

[
{ 'text': '0:', 'value': 'item_0' },
{ 'text': '1:', 'value': 'item_1' },
{ 'text': '2:', 'value': 'item_2' },
{ 'text': '3:', 'value': 'item_3' },
{ 'text': '4:', 'value': 'item_4' },
{ 'text': '5:', 'value': 'item_5' },
{ 'text': '6:', 'value': 'item_6' },
{ 'text': '7:', 'value': 'item_7' },
{ 'text': '8:', 'value': 'item_8' },
{ 'text': '9:', 'value': 'item_9' }
]

Any help or an examlpe of loading via a $ajax() call would be greatly appreciated.  I need to be able to make dynamic loads of  the options list throughout my code.

If I populate the json data manually everything works as expected.

thanks,

mike

**Comment by SentencedToCode** [comment]
I am able to initially populate the drop down menu in  my SelectBoxIt from a JSON object useing "deferred.resolve(arr).  But, when I try to update the drop down menu from another JSON object, the original options do not change. Do I need to ".refresh" at some point?  I can remove the drop down menu items, but then I cannot populate them again.  The only way I can change the drop down menu is remove the data options, and loop through the JSON object with a "listbox.add("option string'), one by one.  My drop downs have over 1000 records, and this takes time.  Please help.
