### ISSUE TITLE
Custom Width of Select

### ISSUE THREAD

**Issue by davidangel** [gfranko/jquery.selectBoxIt.js#176]
Hi there, I'm having trouble figuring out exactly how to have a fixed narrow width on my selectBoxIt. Should I use CSS? That hasn't seemed to work for me. I'm wanting to have a really narrow select box with just a widget icon that opens up to the full list.

Any help would be greatly appreciated.

**Comment by alexforever86** [comment]
I was looking for this same thing. Definitely this works. But the issue now is that, there is a small jump on page loads. Know how to fix this?
