### ISSUE TITLE
SelectBoxIt 100% width

### ISSUE THREAD

**Issue by groodt** [gfranko/jquery.selectBoxIt.js#200]
I wanted to know how to create a SelectBoxIt select that filled 100% of the container. Greg Franko helped me solve my issue.

I've recorded the solution here:
http://jsbin.com/udapic/1/edit

and on SO:
http://stackoverflow.com/questions/18269428/how-to-create-a-100-width-select-with-selectboxit-js/

**Comment by toumsookdev** [comment]
Thank you @groodt and @gfranko
