### ISSUE TITLE
Will this plugin be independent from jQuery UI

### ISSUE THREAD

**Issue by prashathsenthil** [gfranko/jquery.selectBoxIt.js#215]
Hi,

I want to use this plugin but it has jQuery UI as it's dependency which seems to be a huge javascript file.

Will it be possible to use this plugin without jQuery UI.

**Comment by BrianLaughlan** [comment]
Hello,

Is there any update on this? When can we ditch jqueryUI ?

Cheers.

**Comment by Antevirus** [comment]
I tried a custom download with only the jQueryUI Widget Factory, but it doesnt work.

What exactly do i have to select at the custom download of jquery UI ?
