### ISSUE TITLE
Wrong display when using default text + icons

### ISSUE THREAD

**Issue by badulesia** [gfranko/jquery.selectBoxIt.js#224]
Hello.
When using the default text property and icon for each options, default text is displayed with the icon of first option. To reproduce this, just use both the codes of "custom icon support" and "set default text" examples from your website. You'll see "Sample text here" displayed with first icon whereas it's expected to be displayed without. Is it possible not to display an icon for default text ?

In a way, this a consequence of issue #223. I used the code you provided in answer and it works well. Than I just add the default text property and find this new issue.

**Comment by ErickAlexander3** [comment]
This is still an issue that I can't solve
