### ISSUE TITLE
Is there a way to focus the box from javascript?

### ISSUE THREAD

**Issue by rhessinger** [gfranko/jquery.selectBoxIt.js#257]
I'm trying to focus the selectboxit widget using javascript.  On inputs, i can just call `$('#id').focus()`.  This does not work for selectboxit though.

**Comment by smurfs2549** [comment]
hi,@gfranko  
Do u know how to change <span> into <input> , and when i click the input ,the field is active and user may enter text?

**Comment by smurfs2549** [comment]
hi,@gfranko
Do u know how to change '<span>' into '<input>' , and when i click the input ,the field is active and user may enter text?

**Comment by smurfs2549** [comment]
hi,@gfranko
Do u know how to change tag of 'span' into 'input' , and when i click the input ,the field is active and user may enter text?
