### ISSUE TITLE
SelectBoxIt TabIndex Issue

### ISSUE THREAD

**Issue by slickDroid** [gfranko/jquery.selectBoxIt.js#30]
Hi Greg, I am following up on your suggestion from stackOverflow regarding the SelectBoxIt TabIndex Issue I am having. Basically the issue is when tabbing from one form element to the next the Select Box gets ignored in the sequence, but it does work when not using TabIndex in the Inputs.

You said, "my select box tabindex is getting ignored is because SelectBoxIt hides the original select box and replaces it with new HTML that is easier to style (a div element). Hence, the tabindex attribute is not being set on the visible drop down (the div element), only the hidden select box".

Also, I have this line of code I modified from another forum & thought it might be on the right track?

jQuery('div.selectboxit ul').attr("tabindex",-1);

thank you for looking into this And excellent work on the selectBoxIt!

PS: I modified the bootstrap.css file, which may be of interest to others who simply want to add a selectBoxIt drop-down, I wormed out all unnecessary CSS for this instance: http://www.lightupco.com/s/bootstrap_mod.css

**Comment by vsangolli** [comment]
Hi @gfranko ,

It will work for form. What if we don't have form. Just in a page multiple links are available those links will be dynamic. In that case, how we provide tabindex value? Can you please help this case.
