### ISSUE TITLE
What JQuery UI components I need add for jquery.selectBoxIt.js

### ISSUE THREAD

**Issue by volodymyrl** [gfranko/jquery.selectBoxIt.js#324]
Can you specify what JQuery UI components http://jqueryui.com/download/#! I need add for jquery.selectBoxIt.js It doesn't have reason use full JQuery UI library (if I don't use it in my project). Thanks!

**Comment by gfranko** [comment]
You only need the jqueryui widget factory.  Just check the **Widget** checkbox [here](http://jqueryui.com/download/)
