### ISSUE TITLE
Loading over HTTPS

### ISSUE THREAD

**Issue by ejmcatavolt** [gfranko/jquery.selectBoxIt.js#334]
I have migrated my web site to HTTPS and the last nit I can't figure out is that the SelectBoxIt script is not loading since I moved to HTTPS URLs. Since many browsers will not load HTTP content on a HTTPS page, or throw up an annoying dialog, how can I still use this script which is responsible for sizing many of the forms on my website?

Here's the page in question:
https://www.catavolt.com/resources/ebook-real-time-data-eight-discipline-8d-problem-solving-process-manufacturing/

Error I'm getting from console: GET https://gregfranko.com/jquery.selectBoxIt.js/js/jquery.selectBoxIt.min.js net::ERR_TIMED_OUT

When I try to browse to it online, the HTTP comes up instantly. No luck with HTTPS. Do you have any recommendations on how to proceed, or am I doing something wrong?

**Comment by gfranko** [comment]
You really shouldn't be loading SelectBoxIt from my homepage.  You should download the necessary scripts to your web server and host them there.
