### ISSUE TITLE
Incorrect Javascript?

### ISSUE THREAD

**Issue by krngrvr09** [gfranko/jquery.selectBoxIt.js#340]
``jquery.selectBoxIt.core.js`` file has incomplete javascript code. On executing it raises an ``eof`` error.

The file has a missing ``}));`` in the end. This part of the code is present in ``jquery.selectBoxIt.endClosure.js``.

Is this intentional?

**Comment by gfranko** [comment]
You shouldn't be using `jquery.selectBoxIt.core.js` (that file is for development only).  Instead use [jquery.selectBoxIt.js](https://github.com/gfranko/jquery.selectBoxIt.js/blob/master/src/javascripts/jquery.selectBoxIt.js)
