### ISSUE TITLE
use onclick in option

### ISSUE THREAD

**Issue by KinG-InFeT** [gfranko/jquery.selectBoxIt.js#344]
Hi,

Hello ,
I would use the 'click on the options like this:

```
<select>
    <option onclick="alert(1);">test 1</option>
    <option onclick="alert(2);">test 2</option>
</select>
```

but the plugin does not allow Apple to do, you have any idea?

thank you

**Comment by mladimatija** [comment]
You can always use option-click event like this:

```$("select#test").bind({
      "option-click": function(ev, obj) {
        $('this').alert('what-you-want-to-alert');
      }
    });```

**Comment by KinG-InFeT** [comment]
thanks for the answer, but as I do now to pick up the val attribute of the selected option?

**Comment by KinG-InFeT** [comment]
issue!!!!!!!!!!!!!! WITH CHROME NOT WORK THE OPTION-CLICK !!!!
