### ISSUE TITLE
Doesn’t work on Safari on iPad

### ISSUE THREAD

**Issue by martinbean** [gfranko/jquery.selectBoxIt.js#366]
I have a web application with select boxes replaced with selectBoxIt. Looking at the mark-up in Safari’s web inspector on desktop, I can see the plugin has initialised (as the select box is replaced with the selectBoxIt mark-up), but I can’t get to the plugin instance. Whenever I use `.data('selectBox-selectBoxIt')` I get the following error:

> TypeError: undefined is not an object (evaluating 'this.$subCategory.data('selectBox-selectBoxIt').remove')

**Comment by gfranko** [comment]
Make sure you are using the jQuery widget factory!

**Comment by gabdara** [comment]
same issue here, jquery ui 1.12.1

**Comment by gabdara** [comment]
Found the issue in my case.
If you have something like:
```
$('.my-select').selectBoxIt();
```
Now the select class is duplicated and `$('.my-select')` will return 2 elements, `span` and `select`. So you might get `undefined` if you do:
```
$('.my-select').data('selectBox-selectBoxIt');
```
To make sure you get the `selectBoxIt` object do:
```
$('select.my-select').data('selectBox-selectBoxIt');
```
