### ISSUE TITLE
Integrating selectBoxIt with qTip and jQuery form Validation.

### ISSUE THREAD

**Issue by ravimallya** [gfranko/jquery.selectBoxIt.js#82]
Hi Greg. I'm trying to figure out how to implement <a href="http://docs.jquery.com/Plugins/Validation" target="_blank">jQuery validation</a> with <a href="http://craigsworks.com/projects/qtip2/demos/#validation" target="_blank">qTip form validation</a>. <a href="http://jsfiddle.net/ravimallya/akrfv/" target="_blank">This</a> is a jsFiddle demo where, the jQuery validation is not working, if we used selectBoxIt for select options. I tried to use

```
    var inputs = 'input:text, span.selectboxit-container';
```

but, the qTip is not getting hidden after selecting an option.

How can we solve this? Is there any easy way to fix it?

Thanks!
Ravi

**Comment by chinhphan099** [comment]
I had to add some CSS.
Note that: the jQuery Validation **can't validate** for **HIDE elements**.
```
.custom-select select {
  display: block !important;
  position: absolute;
  opacity: 0;
}
```
Check this:
http://codepen.io/chinhphan099/pen/YNNoJY
Hope to help.

Anyway, **How can I style for selecboxit state if there is value within ?**
I meant "The No Value Select" style CSS difference "Has Value Select".

I can cheat by code js to add class.
But it better if plugin support the "Has chosen value state and add one class for this case."
